import streamlit as st
from src.config import Config
from src.gemini_client import GeminiClient
from src.rag_store import RAGStore

# Page Config
st.set_page_config(page_title="Kaggle Mentor AI", page_icon="🤖", layout="centered")

st.title("🤖 Kaggle Mentor AI (Simple)")
st.caption("Simplified version featuring Competition Analyzer, Notebook Explainer, and RAG.")

# Initialize components
if "rag_store" not in st.session_state:
    store = RAGStore()
    store.load_and_index_tips()
    st.session_state.rag_store = store

# Tabs for features
tab1, tab2, tab3 = st.tabs([
    "🏆 Competition Analyzer",
    "📓 Notebook Explainer",
    "📚 Kaggle Tips RAG"
])

# Tab 1: Competition Analyzer
with tab1:
    st.header("Competition Analyzer")
    comp_name = st.text_input("Enter Competition Name (e.g., Titanic, House Prices):")
    if st.button("Analyze Competition"):
        if comp_name:
            st.info(f"Analyzing {comp_name}... (Stub)")
            st.write("**Identified Task Type**: Classification/Regression")
            st.write("**Suggested Models**: XGBoost, LightGBM")
            st.write("**Suggested Validation Strategy**: Stratified 5-Fold CV")
        else:
            st.warning("Please enter a competition name.")

# Tab 2: Notebook Explainer
with tab2:
    st.header("Notebook Explainer")
    code_input = st.text_area("Paste Python Notebook Code here:", height=200)
    if st.button("Explain Code"):
        if code_input:
            st.info("Explaining code... (Stub)")
            st.write("This code sets up a standard machine learning modeling pipeline.")
        else:
            st.warning("Please paste some code first.")

# Tab 3: RAG Knowledge Base
with tab3:
    st.header("Kaggle Tips Knowledge Base")
    st.write("Search or ask questions over the indexed 10 Kaggle tips.")
    query = st.text_input("Ask a question (e.g., How to handle cross-validation?):")
    if st.button("Query Tips"):
        if query:
            st.info(f"Searching tips matching '{query}'... (Stub)")
            retrieved = st.session_state.rag_store.search_similar_tips(query)
            st.write("**Retrieved Context**:")
            for tip in retrieved:
                st.markdown(f"- {tip}")
            st.write("**Response Generated by Gemini**:")
            st.write("This is a synthesized answer explaining standard Kaggle validation tips.")
        else:
            st.warning("Please enter a search query.")
